version: '3'

services:
  app:
    container_name: meetup-app
    build: .
    links:
      - db
    ports:
      - "80:80"
    volumes:
      - .:/opt/meetup:cached
    environment:
      DATABASE_URL: 'mysql://dbuser:dbpass@db/meetup'

  db:
    container_name: meetup-db
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: meetup
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass

volumes:
  db_data:
